### ISSUE TITLE
jTos version demand

### ISSUE THREAD

**Issue by JyuuAra** [hiiwave/Tos-Translater#1]
Hi, Would you please add a" jTOS in En or Tw version" ?  
What data/files are necessary please let me know, thanks.

**Comment by hiiwave** [comment]
Hi, could you provide jTOS language file under release/languageData?

**Comment by JyuuAra** [comment]
Sure, I'm sorry I just get off work.
We're so glad you could help us and really appreciate that!
[languageData.zip](https://github.com/hiiwave/Tos-Translater/files/3030553/languageData.zip)

**Comment by hiiwave** [comment]
Hi I checked the files you uploaded. I'm glad to help but I'm afraid I have to conclude that it's not possible to translate jTOS with this project. The reason is that this project depends on korean mapping and the korean content is not reserved in jTOS language file. Please see [readme#methodology](https://github.com/hiiwave/Tos-Translater#methodology) for more information.

**Comment by JyuuAra** [comment]
Maybe I deleted the KR folder by mistake? Could it be possible if I found Original KR mapping?
I'm sorry I thought it isn't nesscessary so I ignored it.Please check this one, thanks!
[Korean.zip](https://github.com/hiiwave/Tos-Translater/files/3034474/Korean.zip)

**Comment by hiiwave** [comment]
There should be a mapping between japanese and korean. 
Please see the following snippet from twtos language file:
```
ITEM_20180327_000023	結繩臂環	매듭진 암밴드				
ITEM_20180327_000024	如果綁太緊，血有可能不流通。	너무 세게 묶는다면 피가 통하지 않을 수도 있습니다.				
ITEM_20180327_000025	長臂環	긴 암밴드				
```
The format is `UNIQUE_ID CHINESE KOREAN`
Thus I can get the mapping between Chinese sentence and Korean sentence.

However there's no such such mapping in jtos language file.
```
ITEM_20150317_000142	練習用バスタードソード
ITEM_20150317_000143	バスタードソード
ITEM_20150317_000144	ヘビーフランベルジェ
```
There's no Korean component in this data format, hence it could not work.

**Comment by JyuuAra** [comment]
Ah, I see. Can't we just replace JP sentences with EN by same UNIQUE_ID as primary?Thanks anyway!

**Comment by hiiwave** [comment]
No the id is unique on different region. I believe the tos official has the same universal identifier but they didn't release it.
